### ISSUE TITLE
Invalid model spec passes NASBench.is_valid check

### ISSUE THREAD

**Issue by mikelzc1990** [google-research/nasbench#3]
Seems like networks that only have one edge from input to output can pass through the validation check. For example the following network connectivity matrix:
        [[0., 1., 1., 1., 1., 1., 1.],
          [0., 0., 1., 1., 1., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.]],

**Comment by chrisying** [comment]
Hi mikelzc1990,

This is intentional, although it's a fairly degenerate case. The method which we use to construct neural networks from adjacency matrices allows for a single edge from input to output. Here's the part of the code that handles this: https://github.com/google-research/nasbench/blob/master/nasbench/lib/model_builder.py#L297

I agree that it's a bit of a special case and I was originally unsure about whether to include this or now. In the end I left it in since it's still a valid network (the cell is identity and the only convolution is in the convolutional stem).
